
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret mylatitude
  longitude: !secret mylongitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret myelevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret mytimezone
  # Customization file
  
lovelace:
  mode: yaml

# Enables configuration UI
config:

mobile_app:  

history:

# View all events in a logbook
logbook:

# View all logs in home-assistant.log
logger:
  default: error
  logs:
  
sun:

weather:
  - platform: environment_canada
    name: "Environment Canada"
    station: QC/s0000635

tplink:
  discovery: false
  switch:
    host: !secret switch1
    host: !secret dimmer1
 
speedtestdotnet:
  scan_interval:
    hours: 2
  monitored_conditions:
    - ping
    - download
    - upload
    
notify:
  - name: !secret pushbullet_name
    platform: pushbullet
    api_key: !secret pushbullet_apikey

# MQTT broker https://home-assistant.io/docs/mqtt/broker/ 
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

automation: !include automations.yaml
sensor: !include_dir_merge_list sensors/
